### ISSUE TITLE
Allow .coffee files to be access via .coffee extension

### ISSUE THREAD

**Issue by ScottWeinstein** [anaisbetts/SassAndCoffee#28]
It would be a nice feature if we could asses .coffee files via their actual .coffee extension

**Comment by kogir** [comment]
To return the raw contents of the .coffee file, you need to add an IIS Mime-Type for it.  I don't think one has been formally assigned, but you could probably get away with text/plain or text/coffeescript.

If you want to have requests for the .coffee file return the compiled javascript result, I'd recommend writing your own quick HttpModule to do the remapping, or using URL Rewrite http://www.iis.net/download/urlrewrite.  Right now SassAndCoffee always defers to existing files when present and lets IIS serve them as-is.  I don't feel super strongly about it, but would prefer to keep that behavior since it's least surprising.
